### ISSUE TITLE
Greenwave lighting

### ISSUE THREAD

**Issue by pleasanthill17** [dfiel/GreenwaveLighting#3]
Hi, 
Thanks for your work on this. I am running Hassio 0.82.0. On adding your greenwave.py in the custom_components/light/ folder. 

I am seeing this error:
 ERROR (MainThread) [homeassistant.components.light] Error while setting up platform greenwave
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/light/greenwave.py", line 53, in setup_platform
    bulbs = greenwave.grab_bulbs(host, token)
  File "/usr/local/lib/python3.6/site-packages/greenwavereality/greenwavereality.py", line 101, in grab_bulbs
    xml = grab_xml(host, token)
  File "/usr/local/lib/python3.6/site-packages/greenwavereality/greenwavereality.py", line 18, in grab_xml
    parsed = parsed['gwrcmds']['gwrcmd']['gdata']['gip']['room']
KeyError: 'gwrcmds'

Any suggestions is appreciated. Thanks.

**Comment by pleasanthill17** [comment]
Found the solution. Had a old .greenwave file in the config folder. Deleted and synced token. Everything works now. Thanks for your work !!
